kafka installed
improved docker-image versioning capabilites to improve deploy time

diff --git a/helios b/helios
--- a/helios
+++ b/helios
@@ -1,7 +1,7 @@
 #!/bin/bash
+# Exit immediately if a command exits with a non-zero status
+set -e
 
-# Check tool installation
-./scripts/linux/check-tool-installation
 
 # Export environment variables
 export HEL_SETTINGS_FILE="$(pwd)/helios.targets.json"
@@ -9,8 +9,8 @@ export TF_VAR_helios_workspace=$PWD
 export TF_VAR_helios_runner=$PWD/scripts/runner.py
 export TF_DIR=$(pwd)/iac/terraform
 
-
-
+COMMAND=$1
+ENV=$2
 # Validate input arguments
 if [[ -z "$1" ]]; then
     echo "Error: Missing command argument. Must be one of 'plan', 'apply', 'init', 'burn', 'wipe' or 'bootstrap'."
@@ -25,9 +25,7 @@ if [[ "$1" == "burn" ]]; then
 fi
 # Handle 'helios wipe' command separately
 if [[ "$1" == "wipe" ]]; then
-    $PWD/helios burn && \
-    $PWD/helios bootstrap dev && \
-    $PWD/helios apply dev && \
+    $PWD/helios burn && $PWD/helios bootstrap dev && $PWD/helios apply dev
     echo "state was reset, reset your local kubernetes cluster to start fresh"
     exit 1
 fi
@@ -49,15 +47,15 @@ echo "Using Kube Context: $HELIOS_KUBE_CONTEXT"
 
 # Handle 'helios bootstrap' command separately
 if [[ "$1" == "bootstrap" ]] && [[ "$2" =~ ^(dev|stage|prod)$ ]]; then
-    exec $PWD/scripts/linux/bootstrap-cluster $2
+    exec $PWD/scripts/linux/bootstrap-cluster $ENV
     elif [[ ! "$1" =~ ^(plan|apply|init)$ ]]; then
-    echo "Error: Invalid command argument. Must be one of 'plan', 'apply', 'init' or 'helios bootstrap'."
+    echo "Error: Invalid command argument. Must be one of 'plan', 'apply', 'init' or 'bootstrap'."
     exit 1
 fi
 
 
 # Determine the environment
-case "$2" in
+case "$ENV" in
     dev)
         ENV_FILE="./iac/.env"
     ;;
@@ -96,7 +94,12 @@ TF_MODULE: $TF_MODULE
 TF_CLUSTER_MODULE: $TF_MODULE
 EOF
 
+# Check tool installation
+./scripts/linux/check-tool-installation
+./scripts/linux/helios-health-check
+./scripts/linux/helios-source-hash-to-json
 # Execute terraform command
 dotenv -e $ENV_FILE -- terraform -chdir=$TF_DIR init
 dotenv -e $ENV_FILE -- terraform -chdir=$TF_DIR $1 -target=$TF_CLUSTER_MODULE -auto-approve
 dotenv -e $ENV_FILE -- terraform -chdir=$TF_DIR $1 -target=$TF_MODULE -auto-approve
+# dotenv -e $ENV_FILE -- terraform -chdir=$TF_DIR $1 -target=module.dev_env.module.kafka -auto-approve
diff --git a/scripts/linux/bootstrap-cluster b/scripts/linux/bootstrap-cluster
--- a/scripts/linux/bootstrap-cluster
+++ b/scripts/linux/bootstrap-cluster
@@ -1,36 +1,16 @@
 #!/bin/bash
-# set -e
+# Exit immediately if a command exits with a non-zero status
+set -e
 
-KUBE_CONTEXT_NAME=$1
+# Check if the environment variable is provided
+if [ -z "$1" ]; then
+    echo "Usage: $0 <ENV>"
+    exit 1
+fi
 
-# Add Jetstack Helm repo
-helm repo add jetstack https://charts.jetstack.io
-helm repo add linkerd-edge https://helm.linkerd.io/edge
-# Update Helm repos
-helm repo update
+ENV=$1
 
-# # Use specific kubernetes context
-# # Install Cert Manager
-helm upgrade --install cert-manager --repo https://charts.jetstack.io cert-manager --namespace cert-manager --create-namespace --version v1.12.0 --set installCRDs=true
-
-
-
-linkerd check --pre
-
-# helm upgrade --install linkerd-edge/linkerd-crds --create-namespace --namespace linkerd \
-helm upgrade --install linkerd-crds linkerd-edge/linkerd-crds \
-  --create-namespace --namespace linkerd
-
-helm upgrade --install linkerd-control-plane linkerd-edge/linkerd-control-plane \
-  --namespace linkerd \
-  --set proxyInit.runAsRoot=true \
-  --set-file identityTrustAnchorsPEM=./iac/certificates/$KUBE_CONTEXT_NAME/linkerd/ca.crt \
-  --set-file identity.issuer.tls.crtPEM=./iac/certificates/$KUBE_CONTEXT_NAME/linkerd/issuer.crt \
-  --set-file identity.issuer.tls.keyPEM=./iac/certificates/$KUBE_CONTEXT_NAME/linkerd/issuer.key \
-
-linkerd check
-
-helm upgrade --install linkerd-viz linkerd-edge/linkerd-viz \
-  --namespace linkerd-viz --create-namespace
-
-# linkerd viz install | kubectl apply -f - # install the on-cluster metrics stack
+# Run the installation scripts
+./scripts/linux/install-cert-manager
+./scripts/linux/install-linkerd "$ENV"
+./scripts/linux/install-kafka "$ENV"
